name: Hub - Version and Release

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: "Semantic Version Bump Type (major minor patch)"
        default: patch

defaults:
  run:
    working-directory: packages/hub

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "packages/hub/pnpm-lock.yaml"
          # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: git config --global user.name machineuser
      - run: git config --global user.email tech@huggingface.co
      - run: yarn config set version-git-message "ðŸ”– @hugginface/hub v%s"
      - run: yarn config set version-tag-prefix "hub-v"
      - run: yarn version --${{ github.event.inputs.newversion }}
      - run: pnpm publish .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags
